#pragma config(Sensor, S1,     IRSeek,         sensorI2CCustom)
#pragma config(Sensor, S2,     Ultrasonic,     sensorI2CCustom)
#pragma config(Motor,  motorA,          left,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          right,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "stdbot_d.h"

#define wheeldiam 0

float inPerDeg = 360/(PI*wheeldiam);
tIRSeek ir = tIRSeek;
task main()
{
	initWriteMode("log.txt", 1024, true);

	while(true)	{
		nMotorEncoder[left] = 0;
		nMotorEncoderTarget = 720;
		motor[left] = 75;

		while(nMotorRunState[left] != runStateIdle)	{
			readIRSeeker(S1, ir);
			writeInt(ir.rawStrength);
			writeInt((int)(inPerDeg * nMotorEncoder[left]));
		}
	}
}
