#pragma config(Sensor, S1,     EOPD,           sensorAnalogActive)
#pragma config(Sensor, S2,     IRSeeker,       sensorI2CCustom)
#pragma config(Sensor, S3,     LightSensor,    sensorLightActive)
#pragma config(Sensor, S4,     Ultrasonic,     sensorI2CCustom)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Tests various sensors

*	S1- EOPD
*	S2- IRSeeker
*	S3- LightSensor
*	S4- Ultrasonic
*/

//	includes
#include "hitechnic-eopd.h"
#include "hitechnic-irseeker-v2.h"
#include "lego-light.h"
#include "lego-ultrasound.h"

//	#defines
#define LIGHT_HI 325
#define LIGHT_LO 106

//	vars
bool shortRange = false;
int val[4] = {0, 0, 0, 0};

//	funcs
void setup()	{
	//	makes a pretty intro
	nxtDisplayCenteredTextLine(0, "FTC TEAM 5818");
	nxtDisplayCenteredTextLine(1, "Sensor Testing");
	nxtDisplayCenteredTextLine(2, "Press Enter to");
	nxtDisplayCenteredTextLine(3, "change EOPD/LS");
	nxtDisplayCenteredTextLine(4, "mode");
	nxtDisplayCenteredTextLine(6, "Written by");
	nxtDisplayCenteredTextLine(7, "Joe Quigley");

	wait1Msec(5000);

	eraseDisplay();

	nxtDisplayCenteredTextLine(0, "FTC TEAM 5818");
}

void setShortRange()	{
	//	sets EOPD and light sensors to conditions suitable for short ranges
	HTEOPDsetShortRange(EOPD);
	LSsetActive(LightSensor);
}

void setLongRange()	{
	//	sets EOPD and light sensors to conditions suitable for longer ranges
	HTEOPDsetLongRange(EOPD);
	LSsetInactive(LightSensor);
}

int readEOPD(bool raw)	{
	//	reads the EOPD sensor
	//	@param	raw	whether to read raw val or not
	if(raw)	{
		return HTEOPDreadRaw(EOPD);
	}
	else	{
		return HTEOPDreadProcessed(EOPD);
	}
}

int readIRSeekDir()	{
	//	reads IR seeker
	return HTIRS2readDCDir(IRSeeker);
}

int readLegoLight()	{
	//	reads the light sensor
	return LSvalRaw(LightSensor);
}

int readUltrasonic()	{
	//	reads ultrasonic distance
	return USreadDist(Ultrasonic);
}

//	tasks
task main()
{
	//	main task
	nNxtButtonTask = 5000042;

	setup();
	setShortRange();
	clearDebugStream();

	while(true)	{
		/*
		nxtDisplayTextLine(2, "EOPDRaw:%i", readEOPD(true));
		nxtDisplayTextLine(3, "EOPDPRC:%i", readEOPD(false));
		nxtDisplayTextLine(4, "IRSeek: %i", readIRSeekDir());
		nxtDisplayTextLine(5, "Light:  %i", readLegoLight());
		nxtDisplayTextLine(6, "Ultra:  %i", readUltrasonic());

		if(nNxtButtonPressed == 3)	{
			if(shortRange)	{
				setLongRange();
				shortRange = false;
				nxtDisplayTextLine(7, "Long Range Mode ");
			}
			else	{
				setShortRange();
				shortRange = true;
				nxtDisplayTextLine(7, "Short Range Mode");
			}
		}
		*/
		writeDebugStream("%i\n", readLegoLight());
	}
}
