#pragma config(Sensor, S1,     IRSeek,         sensorI2CCustom)
#pragma config(Sensor, S2,     Ultrasonic,     sensorI2CCustom)
#pragma config(Motor,  motorA,          ,          tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          ,          tmotorNXT, openLoop)
#pragma config(Motor,  motorC,          left,             tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "stdbot_d.h"

#define wheeldiam 2.25

float inPerDeg = (PI*wheeldiam)/360.0;
tIRSeek ir = tIRSeek;

task main()
{
	initWriteMode("log.txt", 1024, true);
	nMotorEncoder[left] = 0;
	nMotorEncoderTarget[left] = 3600;
	motor[left] = 15;

	while(nMotorRunState[left] != runStateIdle)	{
		//readIRSeeker(S1, ir);
		writeInt(readUltrasonic(Ultrasonic));
		writeInt((int)((inPerDeg * nMotorEncoder[left])*1000));
		plot((int)(inPerDeg * nMotorEncoder[left]), readUltrasonic(Ultrasonic));
	}

	wait1Msec(5000);
	closeActiveFile();
}
