#pragma config(Sensor, S1,     EOPD,           sensorAnalogActive)
#pragma config(Sensor, S2,     IRSeeker,       sensorI2CCustom)
#pragma config(Sensor, S3,     LightSensor,    sensorLightInactive)
#pragma config(Sensor, S4,     Ultrasonic,     sensorI2CCustom)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-eopd.h"
#include "hitechnic-irseeker-v2.h"
#include "lego-light.h"
#include "lego-ultrasound.h"

void setup()	{
	nxtDisplayTextLine(0, "FTC TEAM 5818");
	nxtDisplayTextLine(1, "Sensor Testing");
	nxtDisplayTextLine(2, "Press Enter to");
	nxtDisplayTextLine(3, "change EOPD/LS");
	nxtDisplayTextLine(4, "mode");
	nxtDisplayTextLine(6, "Written by");
	nxtDisplayTextLine(7, "Joe Quigley");

	wait1Msec(2000);

	eraseDisplay();
}

task main()
{
	setup();
}
