#pragma config(Sensor, S1,     IRSeek,         sensorI2CCustom)
#pragma config(Sensor, S2,     Ultrasonic,     sensorI2CCustom)
#pragma config(Motor,  motorA,          ,          tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          ,          tmotorNXT, openLoop)
#pragma config(Motor,  motorC,          left,             tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "stdbot_d.h"

#define wheeldiam 2.25

float inPerDeg = (PI*wheeldiam)/360.0;

task main()
{
	initWriteMode("log.txt", 1024, true);
	nMotorEncoder[left] = 0;
	nMotorEncoderTarget[left] = 102400;
	motor[left] = 35;

	HTEOPDsetLongRange(Ultrasonic);

	while(nMotorRunState[left] != runStateIdle)	{
		writeInt(readEOPD(Ultrasonic));
		writeInt((inPerDeg * nMotorEncoder[left])*1000);
		nxtDisplayTextLine(0, "measured dist");
		nxtDisplayTextLine(3, "inches");
		nxtDisplayTextLine(4, "actual dist");
		nxtDisplayTextLine(7, "inches");
		nxtDisplayBigTextLine(1, "%i", (219.577+(-62.333 * (readEOPD(Ultrasonic)))));
		nxtDisplayBigTextLine(5, "%f", (inPerDeg * nMotorEncoder[left]));
		//plot((int)(inPerDeg * nMotorEncoder[left]), readUltrasonic(Ultrasonic));
	}

	wait1Msec(5000);
	closeActiveFile();
}
