#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S2,     ultra,          sensorSONAR)
#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Sensor, S4,     eopd,           sensorAnalogActive)
#pragma config(Motor,  mtr_S1_C1_1,     motorA,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorB,        tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/HTEOPD-driver.h"

int readEOPDDist(bool shortRange)	{
	if(shortRange)	{
		//nuting
	}
	else	{
		//nuting
	}
	return SensorValue[eopd];
}

task main()
{
	nxtDisplayCenteredTextLine(1, "NXT Sensor Test ");

}
