#pragma config(Sensor, S2,     EOPD,           sensorI2CCustom)
#pragma config(Sensor, S3,     IRSeeker,       sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "stdbot_d.h"

tIRSeek ir;

task main()
{
	while(true)	{
		readIRSeeker(IRSeeker, ir);
		nxtDisplayTextLine(0, "IRSeek dist");
		nxtDisplayBigTextLine(1, "%i in", ir.rawStrength);
		nxtDisplayTextLine(3, "EOPD dist");
		nxtDisplayBigTextLine(4, "%i units", readEOPD(EOPD));
		nxtDisplayTextLine(6, "%i", ir.dir);
	}
}
