#pragma config(Sensor, S1,     ForwardTouch,   sensorTouch)
#pragma config(Sensor, S2,     BackwardTouch,  sensorTouch)
#pragma config(Motor,  motorB,          m1,            tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          m2,            tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define LEFT 2
#define RIGHT 1
#define ORANGE 3

//para ben

int getSpeed()	{
	nNxtButtonTask = 10;
	bool pressed = false;

	nxtDisplayTextLine(0, "Speed?");
	nxtDisplayTextLine(1, "LEFT-40");
	nxtDisplayTextLine(2, "MID -60");
	nxtDisplayTextLine(3, "RIGH-80");

	while(pressed == false){

  	if(nNxtButtonPressed == LEFT){
  		pressed = true;
  		return 40;
  	}

  	if(nNxtButtonPressed == ORANGE)	{
  		pressed = true;
  		return 60;
  	}

  	if(nNxtButtonPressed == RIGHT){
  		pressed = true;
  		return 80;
  	}
  }
  return 0;

}

task main()
{
	int speed = getSpeed();
	while(true)	{
		if(SensorValue[S1])	{
			speed = abs(speed);
		}
		else if(SensorValue[S2])	{
			speed = -abs(speed);
		}
		motor[m1] = speed;
		motor[m2] = speed;
	}
}
