#pragma config(Sensor, S2,     SensorMux,      sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers\hitechnic-sensormux.h"

//port 1: IRSeeker, v.2 --Flipped
//port 2: Force

#include "drivers\hitechnic-irseeker-v2.h"
#include "drivers\hitechnic-force.h"

//http://www.robotc.net/forums/viewtopic.php?f=52&t=3873

#define irSeekerSensor msensor_S2_1
#define forceSensor    msensor_S2_2

task main(){

	int _force = 0;
	int _direection = 0;

	while(true){

		//...

	}

}
