#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     SensorMux,      sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     scissorLeft,   tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     scissorRight,  tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     leftRear,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     leftFront,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     rightRear,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     rightFront,    tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C4_1,    arm,                  tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,								tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-sensormux.h"
#include "hitechnic-irseeker-v2.h"
#include "hitechnic-force.h"

#define nSteps
#define irSeekerSensor msensor_S2_1
#define forceSensor    msensor_S2_2

int force, dir, count;
int prog[nSteps][4];
bool lFront, lRear, rFront, rRear;

task main()	{
	while(true)	{
		force = HTFreadSensor(forceSensor);
		dir = HTIRS2readACDir(irSeekerSensor);

		lFront = true;
		lRear = true;
		rFront = true;
		rRear = true;

		motor[leftFront] = 75 * sgn(prog[count][0]);
		motor[leftRear] = 75 * sgn(prog[count][1]);
		motor[rightFront] = 75 * sgn(prog[count][2]);
		motor[rightRear] = 75 * sgn(prog[count][3]);

		while(lFront || lRear || rFront || rRear)	{
			if(prog[count][0] <= nMotorEncoder[leftFront])	{
				motor[leftFront] = 0;
				lFront = false;
			}
			if(prog[count][1] <= nMotorEncoder[leftRear])	{
				motor[leftRear] = 0;
				lRear = false;
			}
			if(prog[count][2] <= nMotorEncoder[rightFront])	{
				motor[rightFront] = 0;
				rFront = false;
			}
			if(prog[count][3] <= nMotorEncoder[rightRear])	{
				motor[rightRear] = 0;
				rRear = false;
			}
		}

		count++;
	}

}
