#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     scissorLeft,   tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     scissorRight,  tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     leftRear,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     leftFront,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     rightRear,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     rightFront,    tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C4_1,    arm,                  tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "debug.c"
#include "JoystickDriver.c"

tDHandler debugHandler;

int calcMotorDrive(int joy, int adj)	{
	return((int)((joy/127.0)*adj));
}

task main()
{
	int leftAdjust = 75;
	int rightAdjust = 75;
	int scAdjust = 75;

	initDebug(debugHandler, false, true);
	debug("Debug loaded.", debugHandler);

	while(true)	{
		if(joy1Btn(5))	{
			leftAdjust = 50;
		}
		else if(joy1Btn(7))	{
			leftAdjust = 100;
		}
		else	{
			leftAdjust = 75;
		}
		if(joy1Btn(6))	{
			rightAdjust = 50;
		}
		else if(joy1Btn(8))	{
			rightAdjust = 100;
		}
		else	{
			rightAdjust = 75;
		}

		if(joy2Btn(5))	{
			scAdjust = 50;
		}
		else if(joy2Btn(7))	{
			scAdjust = 100;
		}
		else	{
			scAdjust = 75;
		}

		motor[leftRear] = calcMotorDrive(joystick.joy1_y1, leftAdjust);
		motor[leftFront] = calcMotorDrive(joystick.joy1_y1, leftAdjust);
		motor[rightRear] = calcMotorDrive(joystick.joy1_y2, rightAdjust);
		motor[rightFront] = calcMotorDrive(joystick.joy1_y2, rightAdjust);
		motor[scissorLeft] = calcMotorDrive(joystick.joy2_y1, scAdjust);
		motor[scissorRight] = calcMotorDrive(joystick.joy2_y2,scAdjust);

		if(joy2Btn(8))	{
			servo[arm] = 255;
		}
		else if(joy2Btn(6))	{
			servo[arm] = 0;
		}
		else	{
			servo[arm] = 125;
		}
	}
}
